"""
Release Notes Assistant

Turns raw commit messages and ticket titles/descriptions into
customer-readable release notes using the Gemini API.
"""

import os
from datetime import datetime

from dotenv import load_dotenv
from google import genai

LOG_FILE = "release_notes_log.md"
DISCLAIMER = (
    "\n\n---\n"
    "This output was generated by AI and must be reviewed and approved "
    "by a human before publishing."
)

load_dotenv()
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
client = genai.Client(api_key=GEMINI_API_KEY)


def collect_input():
    """Reads pasted lines until a line with just END, or 'quit' to exit.

    Returns the raw text, or None if the user wants to quit.
    """
    print(
        "\nPaste commit messages and ticket titles/descriptions below "
        "(multiple lines OK).\nType a line with just END when you're "
        "done, or type quit to exit.\n"
    )
    lines = []
    while True:
        line = input()
        if line.strip().lower() == "quit":
            return None
        if line.strip() == "END":
            break
        lines.append(line)
    return "\n".join(lines).strip()


def build_prompt(raw_text):
    return f"""You are a release-notes editor. Turn the raw developer notes
below into clean, customer-readable release notes.

Rules:
- Group entries under these headings only: Features, Fixes, Improvements, Other.
- Rewrite each entry as one short, plain-language sentence a customer could
  understand, with no technical jargon or internal ticket references.
- Omit any heading that has no entries.
- If an entry is too vague or unclear to describe safely without guessing,
  do NOT invent a description. Instead, list it under a heading called
  "Needs Human Review", quoting the original entry exactly as given.

Raw developer notes:
{raw_text}
"""


def generate_release_notes(raw_text):
    prompt = build_prompt(raw_text)
    response = client.models.generate_content(
        model="gemini-flash-latest",
        contents=prompt,
    )
    return response.text.strip() + DISCLAIMER


def log_result(result):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"## {timestamp}\n\n{result}\n\n")


def main():
    print("Release Notes Assistant")
    while True:
        raw_text = collect_input()
        if raw_text is None:
            print("Goodbye!")
            break
        if not raw_text:
            print("Nothing was pasted, so there's nothing to process.")
            continue

        try:
            result = generate_release_notes(raw_text)
        except Exception as e:
            print(f"\nSomething went wrong calling the Gemini API: {e}")
            print("Nothing was logged. You can try again.")
            continue

        print("\n" + result + "\n")
        log_result(result)
        print(f"(Saved to {LOG_FILE})")


if __name__ == "__main__":
    main()
